Add slack invite info to 'Getting Involved' page and social-buttons.
inclusivenaming/website pull request #35
Opened 2021-01-26 20:45 UTC by edwarnicke

2021-01-26 20:59 UTC, justaugustus requested changes
Nitty nits

2021-01-26 20:59 UTC, justaugustus commented on content/get-involved.md
> +**Join the slack** [Get an Invite](https://communityinviter.com/apps/inclusive-naming/invite)
```suggestion
**Join our Slack workspace:** [get an invite](https://communityinviter.com/apps/inclusive-naming/invite)
```

2021-01-26 22:20 UTC, edwarnicke commented on content/get-involved.md
>  **Join the mailing list:** [inclusivenaming@googlegroups.com](https://groups.google.com/g/inclusivenaming)
Would it then make the language consistent by changing:

```suggestion
**Join our mailing list:** [inclusivenaming@googlegroups.com](https://groups.google.com/g/inclusivenaming)
```

2021-02-01 17:42 UTC, justaugustus approved these changes

2021-02-01 17:43 UTC, merged